version: '3.8'

volumes:
  teamcity-database:

services:
  teamcity-database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - teamcity-database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  teamcity-server:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - 8112:8111
    volumes:
      - ./teamcity-server:/data/teamcity_server/datadir
      - ./teamcity-server/logs:/opt/teamcity/logs
    depends_on:
      - teamcity-database

  teamcity-agent:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    volumes:
      - ./teamcity-agent/conf1:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - teamcity-server
